### ISSUE TITLE
Sort uppercase and lowercase together

### ISSUE THREAD

**Issue by phacic** [pappasam/toml-sort#14]
Currently Uppercase are grouped and sorted differently from lowercases.

e.g.

> [tool.poetry.dependencies]
Django = "^2.2"
Jinja2 = "2.11"
Markdown = "^3.2"
arrow = "^0.15"
django-filter = "^2.3"

expected

> [tool.poetry.dependencies]
arrow = "^0.15"
Django = "^2.2"
django-filter = "^2.3"
Jinja2 = "2.11"
Markdown = "^3.2"

**Comment by pappasam** [comment]
Hmm, good point! I'll add a CLI option to ignore case for sorting purposes.

**Comment by pappasam** [comment]
Resolved by [0.19.0](https://pypi.org/project/toml-sort/)

**Comment by phacic** [comment]
Beautifully don't. Thanks for listening
