### ISSUE TITLE
Rename '--check' to '--check-only' or make changes to '--help' message

### ISSUE THREAD

**Issue by Maciej-Zwolinski** [pappasam/toml-sort#24]
As is, `--check` doesn't change the file that is supposed to be sorted, despite `--help` explicitly stating:

"Check if an original file **is** changed by the formatter."

which suggests changes are being made to the original file (they aren't).

Proposed solution: either rename option to indicate it **only checks** if the file is considered sorted or not - `--check-only` or `--is-sorted`, with the latter suggesting no changes and just true/false return value explicitly.

Alternatively, I'd suggest changing the `--help` message to be more clear:

"Check if an original file **would be** changed by the formatter."

**Comment by pappasam** [comment]
The language "silently check if an original file would be changed by the formatter" has been added to the `--help` message
