### ISSUE TITLE
Maintain literal quotes for keys

### ISSUE THREAD

**Issue by jonyscathe** [pappasam/toml-sort#28]
Hey,

Great tool, one slight improvement I would suggest if it isn't too hard is around quoted keys.

Firstly, I think it is great that if you have something like:
```
'key1' = 'value1'
"key2" = "value2"
```
It will get changed to:
```
'key1' = 'value1'
"key2" = "value2"
```
That is great, given that there is no need to put those keys in quotes.
However, I have a case where I do require a `.` within a key.
So for that I define it as a literal quote (single quotes), i.e.,
```
'namespace.package' = 'my_value'
```
And currently toml-sort changes that to:
```
"namespace.package" = 'my_value'
```
So it changes the quoted key from a literal string to a basic string. This isn't the end of the world, but some others I work with have a strong preference for using literal strings in toml rather than basic strings so it looks a bit odd having a file full of single quotes and one string with double quotes.

Also, toml-sort changes the following (one dumb example, and one string from the quoted keys section of the toml spec:
```
'C:\Users\nodejs\templates' = true
'quoted "value"' = "value"
```
to:
```
"C:\Users\nodejs\templates" = true
"quoted \"value\"" = "value"
```
One would argue that changing 'quoted "value"' to "quoted \"value\"" has decreased the readability of that string which is not ideal.
The other string (I accept, no one should ever have a path as a key... but technically it is still valid toml) is more problematic. After toml-sort has changed that from single to double quotes then tomlkit can no longer parse the file.
Interestingly, even if I set that key to `"C:\\Users\\nodejs\\templates"` then toml-sort changes it back to `"C:\Users\nodejs\templates"` which then can't be parsed.

Again, no one should have such a stupid key, and I don't have anything like that (I just have one key with a `.` in it). 
But toml-sort also shouldn't take a parsable input and end up with a non-parsable output.
And it would also be great if toml-sort preserved the string type of the key if a quoted key is required.

**Comment by pappasam** [comment]
Based on my testing, it looks like (at least) as of version `0.22.0`, this has been resolved!
