### ISSUE TITLE
Not compatible with tomlkit 0.8.0

### ISSUE THREAD

**Issue by triumph1** [pappasam/toml-sort#41]
Hi! thanks for creating great tool :)
I think I have encountered an issue whiling upgrading version 0.20.1 -> 0.22.2

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/77367491/213613681-eefc0284-048f-4030-b4b6-a48352512148.png">

it seems it is not compatible with tomlkit 0.8.0 and poetry doesn't upgrade it

**Comment by pappasam** [comment]
Thanks for this issue, it has been resolved in the latest release (by updating our dependency constraints to reflect reality): https://github.com/pappasam/toml-sort/releases/tag/v0.22.3
