### ISSUE TITLE
Python as first item in "tool.poetry.dependencies"

### ISSUE THREAD

**Issue by KyleKing** [pappasam/toml-sort#42]
I would like to use the `--all` option, but it reorders `"python"`, which is first by convention for poetry packages.

```sh
> poetry new tmp
> cd tmp
> poetry add antigravity
> cat pyproject.toml
[tool.poetry]
name = "tmp"
version = "0.1.0"
description = ""
authors = ["Kyle King <KyleKing@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
antigravity = "^0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
> toml-sort pyproject.toml -i -a
> cat pyproject.toml
[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["Kyle King <KyleKing@users.noreply.github.com>"]
description = ""
name = "tmp"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
antigravity = "^0.1"
python = "^3.11"
```

Where, if sorted manually or by `poetry-plugin-sort`, I would expect the dependencies to be sorted as:

```sh
[tool.poetry.dependencies]
python = "^3.11"
antigravity = "^0.1"
```

Would you be interested in a feature that would recognize `tool.poetry.dependencies` in `pyproject.toml` and keep the python dependency first? If so, I would be happy to try to contribute and if so, would probably add some sort of generic hook to override the sort order for edge cases like these

**Comment by pappasam** [comment]
@KyleKing yes, this feature would be great! I think it relates somewhat this this issue as well: https://github.com/pappasam/toml-sort/issues/43
