### ISSUE TITLE
Support checking multiple filenames at the time

### ISSUE THREAD

**Issue by atugushev** [pappasam/toml-sort#7]
Currently with this pre-commit config below toml-sort will fail because it doesn't support checking multiple files at the time, see:

#### Sample of `.pre-commit-config.yaml`
```yml
repos:
  - repo: local
    hooks:
      - id: toml-sort
        name: toml-sort
        entry: toml-sort --check
        language: system
        types: [toml]
```

#### Actual result
```console
$ touch foo.toml

$ pre-commit run --all-files toml-sort
toml-sort................................................................Failed
- hook id: toml-sort
- exit code: 2

Usage: toml-sort [OPTIONS] [FILENAME]
Try 'toml-sort --help' for help.
Error: Got unexpected extra arguments (pyproject.toml foo.toml)
Usage: toml-sort [OPTIONS] [FILENAME]
Try 'toml-sort --help' for help.
```

Would you be interested in this feature? If it a yes I could send a PR shortly. Thanks for the awesome linter!

**Comment by pappasam** [comment]
Yes, I'm very interested in this feature! Thanks for the issue and I look forward to the PR :+1:

**Comment by atugushev** [comment]
Could you help me with a couple edge cases? What would be the output of the following commands?

1. `toml-sort foo.toml bar.toml`
1. `toml-sort foo.toml bar.toml --output=-`

**Comment by pappasam** [comment]
To keep things simple, I think multiple arguments should only be supported if the `--in-place` or `--check` options are are used.

In all other cases, we should accept only 1 argument.

**Comment by atugushev** [comment]
Make sense. Thanks for the help!

**Comment by pappasam** [comment]
You're probably already looking into this, but in case you're not, I'd pay special attention to click's variadic arguments: https://click.palletsprojects.com/en/7.x/arguments/#variadic-arguments

**Comment by atugushev** [comment]
Thanks for suggestions! Please review #8 when you have time.
